### ISSUE TITLE
Newznab search categories are not retained through restarts

### ISSUE THREAD

**Issue by gersilex** [SickRage/old-sickrage-issues#1215]
When changing the Newznab CatIDs within the settings, SickRage searches the additional CatIDs after saving, but after a restart of SickRage, only the defaults are being searched again (5030, 5040).

**Branch/Commit**: master 00bb35e92a5b2909fafaa5ee6255ce6699ff8ae7
**OS**: 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux
**What you did**:
- Open search provider settings
- choose "NZBGeek" Provider in advanced settings
- select CatIDs 5020, 5030, 5040
- Update Categories
- Save to config
  (sickrage successfully asks for all 3 CatIDs on API requests)
- Restart SickRage with cleanly via menu
  (sickrage only queries the default 5030 and 5040 CatIDs again, settings reflect this behaviour)

**What happened**:
- SickRage did not save or load the CatID selection
  or
- Sickrage overwrote the settings at startup

**What you expected**:
- The CatIDs are being saved to config 
- The CatIDs are loaded back from config on SickRage start

**Logs**:

```
# Initial run, before changing settings
DEBUG    SEARCHQUEUE-MANUAL-176941 :: [NZBGeek] :: [00bb35e] GET URL: https://api.nzbgeek.info/api?apikey=**********&tvdbid=176941&season=1&maxage=500&cat=5030%2C5040&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]

# updating the settings to use 5020 as well
DEBUG    Thread-13 :: [00bb35e] GET URL: https://api.nzbgeek.info/api?apikey=**********&t=caps [Status: 200]

# saved and immediately test with clean cache
DEBUG    SEARCHQUEUE-MANUAL-176941 :: [NZBGeek] :: [00bb35e] GET URL: https://api.nzbgeek.info/api?apikey=**********&maxage=500&cat=5020%2C5030%2C5040&limit=100&t=tvsearch&offset=0 [Status: 200]

# restart sickrage
INFO     MAIN :: [00bb35e] Starting SickRage [master] using '/home/sickrage/sickrage/config.ini'

# manually search again, API request ist wrong again and using only default CatIDs 5030 and 5040
SEARCHQUEUE-MANUAL-176941 :: [NZBGeek] :: [00bb35e] GET URL: https://api.nzbgeek.info/api?apikey=**********&tvdbid=176941&season=1&maxage=500&cat=5030%2C5040&limit=100&t=tvsearch&offset=0&ep=1 [Status: 200]

```

If I can help you in any other way, please let me know. Thank you in advance for looking into this. You can give me a fork, branch or patch to test, if you want to.

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@gersilex Could you try to add NZBGeek as a custom nzb provider (not the build-in one) and see if that works fine, or has the same issue.?

**Comment by fernandog** [comment]
Its an old known issue from PR 998.
Seems wont be fixed soon.

**Comment by gersilex** [comment]
@neoatomic Createing a custom provider works well. This will work as a workaround for now.

I understand the problems for english-only watchers with the **foreign** category. Is this a won't-fix or should we discuss about possible ways to implement something (not thinking about just changing the defaults, this would force original-language-watchers to exclude every unwanted language)?

**Comment by neoatomic** [comment]
@gersilex We cant include all other cat's (foreign etc.) by default as that courses issues. (load/feed limitations etc.)

When you add a "new" indexer the cat's 5030 and 5040 get added by default, to prevent that users forget to set any cat's. 
However it seems that this is not working correctly with the build-in providers. Or that the changes are not saved. So that might be a bug.

Hope @miigotu can do a quick check to see if that is indeed the case.

**Comment by miigotu** [comment]
Previously, you couldn't select categories for built in providers at all.

There is some funkyness with the JavaScript and how the config is laid out.

For now just add a custom provider.

And btw, PR 998 didn't break anything.

**Comment by neoatomic** [comment]
Going to close this for now, as there isn't an easy fix... Meanwhile just add any build-in provider as an custom provider if you need more CAT's than the default 5030 & 5040.

**Comment by OmgImAlexis** [comment]
If someone can give me a clean simple example on how to reproduce this I'll have a stab at fixing it.

**Comment by OmgImAlexis** [comment]
@miigotu any chance this isn't being saved to the config.ini? Seems like it may not be a js issue.

**Comment by miigotu** [comment]
idk for sure, but that whole section of js is a mess. I need to rework some of the python side too

**Comment by gersilex** [comment]
@OmgImAlexis Reproduction steps are in my original post in **What you did**.

Do you need further information or maybe a gif showing the steps and resulting behaviour on my system?

**Comment by OmgImAlexis** [comment]
@gersilex that may help. I only use torrents myself with public sites so I don't really know how most of this stuff works but I can fix the code if I can workout how it's meant to go. :+1:

**Comment by gersilex** [comment]
@OmgImAlexis Alright, will do it this evening (CET+1) so that's in about 10 hours from now.

**Comment by OmgImAlexis** [comment]
Sounds good, thanks. :+1:

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage#998 made it possible to change the categories of built in newznab providers, however it seems they arent always saving

**Comment by gersilex** [comment]
Sorry, I currently have issues with SickRage. While restarting for the demonstration it refuses to start again, because it has problems with the escaped newline in the file mentioned below:

```
(virtualenv)sickrage@server:~ $ python sickrage/SickBeard.py |& ccze -A
Traceback (most recent call last):
  File "sickrage/SickBeard.py", line 94, in <module>
    import sickbeard
  File "/home/sickrage/sickrage/sickbeard/__init__.py", line 38, in <module>
    from sickbeard import providers
  File "/home/sickrage/sickrage/sickbeard/providers/__init__.py", line 25, in <module>
    from sickbeard.providers import btn, womble, thepiratebay, torrentleech, kat, iptorrents, torrentz, \
EOFError: EOF read where object expected
```

I'll need to fix it before I can do it for you. Maybe you can just try my textual reproduction steps from the original post. Sorry for that.

**Comment by miigotu** [comment]
js bug. It saves to the ini until the next time you return to the provider settings, where the categories are not populated

**Comment by gersilex** [comment]
This is fixed in current sickrage builds. Thank you!
