### ISSUE TITLE
Not able to delete shows

### ISSUE THREAD

**Issue by mvanbaak** [SickRage/old-sickrage-issues#625]
When I try to delete a show (From the homepage I click on a show, and click the 'remove' button on top)

No matter if I select 'remove files' or not, it gives the same error:

```
2016-01-24 23:32:08 Thread-45 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 1596, in deleteShow
    error, show = Show.delete(show, full)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/show_queue.py", line 173, in removeShow
    if all([item, item.show, item != self.currentItem, show.indexerid == item.show.indexerid]):
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [aeffe26]
```

I'm running the latest master on a synology installed with sickbeard-custom

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
@mvanbaak If you go to mass update there you can also delete the show. Try if it works there.

**Comment by mvanbaak** [comment]
Also did not work. But this morning it worked, on both places (as I tried first, and the mass update)

I think I know what's wrong. When I tried yesterday, SR was adding some shows from disk (I reinstalled to switch to the new repo). So while it has a queue of shows to add, you cannot remove shows. This also explains the error (NoneType object has no attribute 'indexerid') as the queue holds directories that SR not yet processed.

**Comment by labrys** [comment]
@mvanbaak When you delete/remove a show it gets queued.  The actual removal/deletion happens later once it gets to that item in the queue.  The error gets raised if you queue up show for removal/deletion more than once (e.g. remove and delete, or click the button more than once).  If SickRage has other actions (such as add shows) in the queue it may be a while before it gets around to processing them.  We are looking into ways to improve the feedback for this process both to prevent these kinds of errors and to make it more apparent when an action is queued.

**Comment by mvanbaak** [comment]
@labrys I thought it worked like that, but I can reproduce the error.
These are the steps to reproduce it:

- Install sickrage from scratch using master of sickrage/SickRage
- Add shows using 'Add existing shows' and point it to my /data/Video/Series (holding 40 shows, with a total of 2000 episodes)
- Let it index a couple of shows. The home screen now shows these shows with poster, and all the others with the sickrage logo
- Open one of the already indexed shows
- Click 'remove' on top (I made very sure I clicked only once)
Bam, you get the error.

When I wait for sickrage to have indexed all shows, I can remove shows without errors

**Comment by papampi** [comment]
Sickrage on QNAS TVS-863.
```
SickRage Version:	Branch: master
Commit: 3f0efd1338faf8796fd355bada4f546ec1cb5ed6
Version: 2016.01.23-1
Python Version:	2.7.11 (default, Jan 9 2016, 16:55:40) [GCC 4.8.5]
SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
Locale:	None.None
 	 
 	 
User:	admin
Program Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage
Configuration File:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/config.ini
Database:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/sickbeard.db
Cache Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/cache
Log Directory:	/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config/Logs
Arguments:	['--daemon', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/config', '--pidfile', '/tmp/SickBeard-TVRage.pid']
```

remove show error log : 
```
2016-01-26 12:23:48 Thread-68 :: Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 282, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/webserve.py", line 1596, in deleteShow
    error, show = Show.delete(show, full)
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickrage/show/Show.py", line 51, in delete
    sickbeard.showQueueScheduler.action.removeShow(show, bool(remove_files))
  File "/share/CACHEDEV1_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/show_queue.py", line 173, in removeShow
    if all([item, item.show, item != self.currentItem, show.indexerid == item.show.indexerid]):
AttributeError: 'NoneType' object has no attribute 'indexerid'
 [3f0efd1]
```

remove show web page output :
```
Oops
You have reached this page by accident, please check the url.
```
As mentioned above this just happenes when sickrage is adding existing shows, when its finishes its job all works as it should.

**Comment by labrys** [comment]
@mvanbaak @papampi I haven't had a chance to test this yet, but I when I do I'll update you.  I think the problem here is the converse of the double removal of a show.  Until the indexing process is finished the isn't available to query, those the None.

**Comment by Symbiot78** [comment]
same issue here on debian. 

```
2016-02-05 21:09:44 Thread-33 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickbeard/sickbeard/processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickbeard/sickbeard/processTV.py", line 544, in process_media
    result.result = processor.process()
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 1009, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/opt/sickbeard/sickbeard/helpers.py", line 1700, in isFileLocked
    f = io.open(checkfile, 'rb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 136: ordinal not in range(128)
 [72f6af7]
2016-02-05 21:09:30 Thread-51 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickbeard/sickbeard/webserve.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/sickbeard/sickbeard/webserve.py", line 2281, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type
  File "/opt/sickbeard/sickbeard/processTV.py", line 265, in processDir
    process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result)
  File "/opt/sickbeard/sickbeard/processTV.py", line 544, in process_media
    result.result = processor.process()
  File "/opt/sickbeard/sickbeard/postProcessor.py", line 1009, in process
    if not helpers.isFileLocked(self.file_path, False):
  File "/opt/sickbeard/sickbeard/helpers.py", line 1700, in isFileLocked
    f = io.open(checkfile, 'rb')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 136: ordinal not in range(128)
 [72f6af7]
```

**Comment by duramato** [comment]
@Symbiot78 your is a totally diferent issue , you need to set your sys locale as utf-8

**Comment by neoatomic** [comment]
Is this still happening on the most recent version.?

**Comment by papampi** [comment]
It was happening to me when there were lots of shows adding, dont know if its still there or not.

**Comment by mvanbaak** [comment]
Same here. At the moment i cant test it but this weekend i can by re-adding all shows

**Comment by Symbiot78** [comment]
I switched to Dev branch and haven't seen the issue since.

De aller venligste,

Martin




On Thu, Mar 10, 2016 at 10:00 AM -0800, "Michiel van Baak" <notifications@github.com> wrote:





Same here. At the moment i cant test it but this weekend i can by re-adding all shows

Sent from my iPhone

> On 10 Mar 2016, at 17:24, Payam Nab <notifications@github.com> wrote:
>
> It was happening to me when there were lots of shows adding, dont know if its still there or not.
>
> —
> Reply to this email directly or view it on GitHub.
>


---
